export type LegacyContentPageKey =
  | "index"
  | "nosotros"
  | "menu"
  | "takeout"
  | "delivery";

export type LegacyPageKey = LegacyContentPageKey | "order";

type RouteState = {
  bodyId: string;
  bodyExtraClasses: string[];
};

export const LEGACY_BODY_CLASS = [
  "tweak-site-width-option-full-background",
  "tweak-icon-weight-light",
  "tweak-site-ajax-loading-enable",
  "ancillary-header-top-left-layout-horizontal",
  "ancillary-header-top-center-layout-stacked",
  "ancillary-header-top-right-layout-horizontal",
  "ancillary-header-bottom-left-layout-stacked",
  "ancillary-header-bottom-center-layout-horizontal",
  "ancillary-header-bottom-right-layout-horizontal",
  "ancillary-header-branding-position-top-center",
  "ancillary-header-tagline-position-bottom-center",
  "ancillary-header-primary-nav-position-top-left",
  "ancillary-header-secondary-nav-position-top-right",
  "ancillary-header-social-position-hide",
  "ancillary-header-search-position-hide",
  "ancillary-header-cart-position-top-right",
  "ancillary-header-account-position-hide",
  "tweak-header-primary-nav-hover-style-fade",
  "tweak-header-primary-nav-button-style-solid",
  "tweak-header-primary-nav-button-shape-square",
  "tweak-header-secondary-nav-hover-style-fade",
  "tweak-header-secondary-nav-button-style-solid",
  "tweak-header-secondary-nav-button-shape-square",
  "tweak-header-search-style-underlined",
  "tweak-header-search-placeholder-show",
  "tweak-header-cart-style-text",
  "tweak-header-account-style-text",
  "tweak-index-nav-style-none",
  "tweak-index-nav-position-right",
  "tweak-index-nav-text-show",
  "tweak-index-page-fullscreen-none",
  "tweak-index-page-scroll-indicator-none",
  "tweak-index-page-scroll-indicator-icon-arrow",
  "tweak-index-page-scroll-indicator-icon-weight-hairline",
  "tweak-index-gallery-layout-split",
  "tweak-index-gallery-spacing-sides-show",
  "tweak-index-gallery-spacing-top-bottom-show",
  "tweak-index-gallery-fixed-height",
  "tweak-index-gallery-apply-bottom-spacing",
  "tweak-index-gallery-hover-style-fade",
  "tweak-index-gallery-controls-small-arrows",
  "tweak-index-gallery-controls-icon-weight-hairline",
  "tweak-index-gallery-indicators-lines",
  "tweak-index-gallery-autoplay-enable",
  "tweak-index-gallery-transition-fade",
  "tweak-index-gallery-content-position-middle-left",
  "tweak-index-gallery-content-text-alignment-left",
  "tweak-footer-show",
  "tweak-footer-layout-stacked",
  "tweak-footer-layout-columns-auto",
  "tweak-footer-stacked-alignment-center",
  "tweak-mobile-bar-top-fixed",
  "ancillary-mobile-bar-branding-position-top-left",
  "ancillary-mobile-bar-menu-icon-position-top-right",
  "tweak-mobile-bar-menu-icon-hamburger",
  "ancillary-mobile-bar-search-icon-position-hide",
  "ancillary-mobile-bar-cart-position-top-right",
  "tweak-mobile-bar-cart-style-text",
  "ancillary-mobile-bar-account-position-hide",
  "tweak-mobile-bar-account-style-text",
  "tweak-mobile-overlay-slide-origin-right",
  "tweak-mobile-overlay-close-show",
  "tweak-mobile-overlay-menu-primary-button-style-solid",
  "tweak-mobile-overlay-menu-primary-button-shape-square",
  "tweak-mobile-overlay-menu-secondary-button-style-solid",
  "tweak-mobile-overlay-menu-secondary-button-shape-square",
  "tweak-quote-block-alignment-left",
  "tweak-social-icons-style-solid",
  "tweak-social-icons-shape-square",
  "hide-album-share-link",
  "tweak-blog-meta-primary-none",
  "tweak-blog-meta-secondary-date",
  "tweak-blog-list-style-grid",
  "tweak-blog-list-separator-show",
  "tweak-blog-list-alignment-left",
  "tweak-blog-list-item-image-show",
  "tweak-blog-list-item-image-aspect-ratio-grid-23-standard-vertical",
  "tweak-blog-list-item-image-aspect-ratio-stacked-11-square",
  "tweak-blog-list-item-title-show",
  "tweak-blog-list-item-excerpt-show",
  "tweak-blog-list-item-body-show",
  "tweak-blog-list-item-readmore-inline",
  "tweak-blog-list-item-meta-position-below-title",
  "tweak-blog-list-pagination-link-label-show",
  "tweak-blog-list-pagination-link-icon-show",
  "tweak-blog-list-pagination-link-icon-weight-light",
  "tweak-blog-item-alignment-center",
  "tweak-blog-item-meta-position-below-title",
  "tweak-blog-item-share-position-below-content",
  "tweak-blog-item-pagination-link-label-show",
  "tweak-blog-item-pagination-link-title-show",
  "tweak-blog-item-pagination-link-meta-hide",
  "tweak-blog-item-pagination-link-icon-weight-light",
  "event-thumbnails",
  "event-thumbnail-size-23-standard-vertical",
  "event-date-label",
  "event-list-show-cats",
  "event-list-date",
  "event-list-time",
  "event-list-address",
  "event-list-icalgcal-links",
  "event-excerpts",
  "event-list-cta-button",
  "event-item-back-link",
  "gallery-design-grid",
  "aspect-ratio-43-four-thirds",
  "lightbox-style-light",
  "gallery-navigation-bullets",
  "gallery-info-overlay-show-on-hover",
  "gallery-aspect-ratio-32-standard",
  "gallery-arrow-style-no-background",
  "gallery-transitions-fade",
  "gallery-show-arrows",
  "gallery-auto-crop",
  "tweak-product-list-image-aspect-ratio-23-standard-vertical",
  "tweak-product-list-item-hover-behavior-show-alternate-image",
  "tweak-product-list-meta-position-overlay",
  "tweak-product-list-mobile-meta-position-under",
  "tweak-product-list-meta-alignment-under-left",
  "tweak-product-list-meta-alignment-overlay-center-left",
  "tweak-product-list-show-title",
  "tweak-product-list-show-price",
  "tweak-product-list-filter-display-left-side",
  "tweak-product-list-filter-alignment-left",
  "tweak-product-item-nav-show-pagination-only",
  "tweak-product-item-nav-pagination-style-titles",
  "tweak-product-item-nav-breadcrumb-alignment-left",
  "tweak-product-item-nav-pagination-alignment-right",
  "tweak-product-item-gallery-position-right",
  "tweak-product-item-gallery-design-stacked",
  "tweak-product-item-gallery-aspect-ratio-34-three-four-vertical",
  "tweak-product-item-gallery-thumbnail-alignment-left",
  "tweak-product-item-details-alignment-left",
  "tweak-product-item-details-show-title",
  "tweak-product-item-details-show-price",
  "tweak-product-item-details-show-excerpt",
  "tweak-product-item-details-excerpt-position-below-add-to-cart-button",
  "tweak-product-item-details-show-share-buttons",
  "tweak-product-item-details-show-variants",
  "tweak-product-item-details-show-quantity",
  "tweak-product-item-details-options-style-square",
  "tweak-product-item-details-show-add-to-cart-button",
  "tweak-product-item-details-add-to-cart-button-style-outline",
  "tweak-product-item-details-add-to-cart-button-shape-square",
  "tweak-product-item-details-add-to-cart-button-padding-small",
  "tweak-product-item-image-zoom-enabled",
  "tweak-product-item-image-zoom-behavior-click",
  "tweak-product-item-lightbox-enabled",
  "tweak-related-products-image-aspect-ratio-11-square",
  "tweak-related-products-meta-alignment-under-center",
  "tweak-product-badge-style-none",
  "tweak-product-badge-position-top-left",
  "tweak-product-badge-inset-floating",
  "newsletter-style-custom",
  "hide-opentable-icons",
  "opentable-style-dark",
  "small-button-style-solid",
  "small-button-shape-square",
  "medium-button-style-solid",
  "medium-button-shape-square",
  "large-button-style-solid",
  "large-button-shape-square",
  "image-block-poster-text-alignment-center",
  "image-block-card-dynamic-font-sizing",
  "image-block-card-content-position-center",
  "image-block-card-text-alignment-left",
  "image-block-overlap-dynamic-font-sizing",
  "image-block-overlap-content-position-center",
  "image-block-overlap-text-alignment-left",
  "image-block-collage-dynamic-font-sizing",
  "image-block-collage-content-position-top",
  "image-block-collage-text-alignment-left",
  "image-block-stack-dynamic-font-sizing",
  "image-block-stack-text-alignment-left",
  "button-style-solid",
  "button-corner-style-pill",
  "tweak-product-quick-view-button-style-docked",
  "tweak-product-quick-view-button-position-bottom",
  "tweak-product-quick-view-lightbox-excerpt-display-hide",
  "tweak-product-quick-view-lightbox-show-arrows",
  "tweak-product-quick-view-lightbox-controls-weight-light",
  "tweak-share-buttons-style-icon-only",
  "tweak-share-buttons-icons-show",
  "tweak-share-buttons-labels-show",
  "tweak-share-buttons-counts-show",
  "native-currency-code-mxn",
  "collection-type-page",
  "collection-layout-default",
  "mobile-style-available",
  "sqs-has-custom-cart",
  "has-logo-image",
  "has-social",
  "enable-load-effects",
  "has-primary-nav",
  "has-secondary-nav",
].join(" ");

const routeStateMap: Record<LegacyPageKey, RouteState> = {
  index: {
    bodyId: "collection-5ef548dfcb4a5e5db1fd29aa",
    bodyExtraClasses: ["collection-5ef548dfcb4a5e5db1fd29aa", "homepage"],
  },
  nosotros: {
    bodyId: "collection-5ef55ad267b9b669de799369",
    bodyExtraClasses: ["collection-5ef55ad267b9b669de799369"],
  },
  menu: {
    bodyId: "collection-5efa626459f66249c4dc79da",
    bodyExtraClasses: ["collection-5efa626459f66249c4dc79da"],
  },
  takeout: {
    bodyId: "collection-5ef55e89e2d6737ff9de69cc",
    bodyExtraClasses: ["collection-5ef55e89e2d6737ff9de69cc"],
  },
  delivery: {
    bodyId: "collection-5ef55ebe6f24095395aefffb",
    bodyExtraClasses: ["collection-5ef55ebe6f24095395aefffb"],
  },
  order: {
    bodyId: "",
    bodyExtraClasses: [],
  },
};

export const knownBodyExtraClasses = [
  "collection-5ef548dfcb4a5e5db1fd29aa",
  "collection-5ef55ad267b9b669de799369",
  "collection-5efa626459f66249c4dc79da",
  "collection-5ef55e89e2d6737ff9de69cc",
  "collection-5ef55ebe6f24095395aefffb",
  "homepage",
];

export function getRouteState(page: LegacyPageKey) {
  return routeStateMap[page];
}
